//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebSerwis")]
    public interface IWebSerwis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSerwis/Silinia", ReplyAction="http://tempuri.org/IWebSerwis/SiliniaResponse")]
        int Silinia(int wartosc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSerwis/Silinia", ReplyAction="http://tempuri.org/IWebSerwis/SiliniaResponse")]
        System.Threading.Tasks.Task<int> SiliniaAsync(int wartosc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebSerwisChannel : Klient1.ServiceReference1.IWebSerwis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSerwisClient : System.ServiceModel.ClientBase<Klient1.ServiceReference1.IWebSerwis>, Klient1.ServiceReference1.IWebSerwis {
        
        public WebSerwisClient() {
        }
        
        public WebSerwisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSerwisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSerwisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSerwisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Silinia(int wartosc) {
            return base.Channel.Silinia(wartosc);
        }
        
        public System.Threading.Tasks.Task<int> SiliniaAsync(int wartosc) {
            return base.Channel.SiliniaAsync(wartosc);
        }
    }
}
